In [2]:
import tensorflow as tf 
hello = tf.constant("hello TensorFlow!") 
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'hello TensorFlow!'>

In [22]:
import tensorflow as tf 

c1 = []
n = 10

def matpow(M, n):
    if n < 1: #Abstract cases where n < 1
        return M
    else:
        return tf.matmul(M, matpow(M, n-1))

with tf.device('/cpu:0'):
    a = tf.Variable(tf.random.uniform(shape=(1000, 1000)), name="a")
    b = tf.Variable(tf.random.uniform(shape=(1000, 1000)), name="b")
    c1.append(matpow(a, n))
    c1.append(matpow(b, n))

print(a)
print(b)
print(c1)

<tf.Variable 'a:0' shape=(1000, 1000) dtype=float32, numpy=
array([[0.5637038 , 0.7629392 , 0.58125234, ..., 0.48616135, 0.6173711 ,
        0.44464135],
       [0.04005599, 0.5092845 , 0.15481448, ..., 0.6065867 , 0.24032891,
        0.10305655],
       [0.84621596, 0.41518164, 0.05496132, ..., 0.4236635 , 0.6091366 ,
        0.06446958],
       ...,
       [0.6995648 , 0.01264739, 0.10407436, ..., 0.01015449, 0.39236236,
        0.00505841],
       [0.15692604, 0.16930914, 0.8320383 , ..., 0.4741348 , 0.710225  ,
        0.48877943],
       [0.26343536, 0.39365005, 0.8493736 , ..., 0.81189585, 0.12095618,
        0.20133686]], dtype=float32)>
<tf.Variable 'b:0' shape=(1000, 1000) dtype=float32, numpy=
array([[0.39116824, 0.65268624, 0.55746984, ..., 0.15399349, 0.5247302 ,
        0.05425489],
       [0.4419124 , 0.9434649 , 0.33738732, ..., 0.80543494, 0.95120263,
        0.65117264],
       [0.69222796, 0.7623178 , 0.8590673 , ..., 0.42300975, 0.14126492,
        0.90362084],
     

In [23]:
tf.device("cpu:0") == tf.device("/cpu:0")

False

In [24]:
tf.device("/cpu:0")

In [25]:
import tensorflow as tf

print(tf.test.is_gpu_available())
print(tf.test.is_built_with_cuda())

False
True


In [30]:
tf.config.list_physical_devices('GPU') == list()

True

In [27]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [6]:
tf.test.gpu_device_name()

''

In [7]:
import tensorflow as tf

tf.test.is_gpu_available(
    cuda_only=False
    
)


False

In [9]:
# https://stackoverflow.com/a/48394195/5270873
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11639737994969878498
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 16547017043734837967
physical_device_desc: "device: XLA_CPU device"
]


In [10]:
# https://stackoverflow.com/a/49463370/5270873
import tensorflow as tf0
if tf.test.gpu_device_name():
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
else:
    print("Please install GPU version of TF")

Please install GPU version of TF
